// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order/order.proto

package order

type Order struct {
	Status          string
	TotalPrice      *MonetaryAmount
	TotalTax        *MonetaryAmount
	Taxes           []*Tax
	DeliveryAddress *Address
	BillingAddress  *Address
	PaymentDetails  []*PaymentDetails
	LineItems       []*LineItem
	Properties      map[string]interface{}
}

type Address struct {
	Name         string
	AddressLine1 string
	AddressLine2 string
	PostCode     string
	City         string
	CountryCode  string
	Properties   map[string]interface{}
}

type PaymentDetails struct {
	SubscriptionId  string
	TransactionCode string
	Amount          *MonetaryAmount
	Properties      map[string]interface{}
}

type LineItem struct {
	ProductId          string
	ProductDescription string
	Count              int32
	ItemPrice          *MonetaryAmount
	TotalPrice         *MonetaryAmount
	ItemTaxes          []*Tax
	TotalTaxes         []*Tax
	Properties         map[string]interface{}
}

type Tax struct {
	Code   string
	Amount *MonetaryAmount
}

type MonetaryAmount struct {
	Value    int64
	Currency string
}
