version: '3'
services:
  documentservice:
    image: gcr.io/sap-se-commerce-arch/documentservice:latest
    restart: always
    environment:
      - DB_ADDR=postgres:5432
    ports:
      - "8000:8000"
    depends_on: 
      - postgres
  postgres:
    image: postgres
    restart: always
    volumes:
      - /private/var/lib/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"