version: '3'
services:
  documentservice:
    image: gcr.io/sap-se-commerce-arch/documentservice:latest
    restart: always
    environment:
      - DB_SERVER_ADDR=postgres:5432
      - LISTEN_ADDR=:80
    ports:
      - "8000:80"
    depends_on: 
      - postgres
  processservice:
    image: gcr.io/sap-se-commerce-arch/processservice:latest
    restart: always
    environment:
      - DB_SERVER_ADDR=postgres:5432
      - DOCUMENTSERVICE_URL=http://documentservice
      - MSG_SERVER_URL=amqp://guest:guest@rabbitmq:5672/
      - LISTEN_ADDR=:80
    ports:
      - "8001:80"
    depends_on: 
      - documentservice
      - rabbitmq
  processengine:
    image: gcr.io/sap-se-commerce-arch/processengine:latest
    restart: always
    environment:
      - MSG_SERVER_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on: 
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    volumes:
      - /private/var/lib/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5673:5673"
      - "15672:15672"      
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - /private/var/lib/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"