version: '3'
services:
  documentservice:
    image: gcr.io/sap-se-commerce-arch/documentservice:latest
    restart: always
    environment:
      - DB_ADDR=postgres:5432
      - LISTEN_ADDR=:80
    ports:
      - "8000:80"
    depends_on: 
      - postgres
  processservice:
    image: gcr.io/sap-se-commerce-arch/processservice:latest
    restart: always
    environment:
      - DOCUMENTSERVICE_URL=http://documentservice
      - LISTEN_ADDR=:80
    ports:
      - "8001:80"
    depends_on: 
      - documentservice
  postgres:
    image: postgres
    restart: always
    volumes:
      - /private/var/lib/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"