---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: actionhandler
  namespace: lw  
spec:
  selector:
    matchLabels:
      app: actionhandler
  replicas: 1 
  template:
    metadata:
      labels:
        app: actionhandler
    spec:
      containers:
      - name: actionhandler
        image: gcr.io/sap-se-commerce-arch/actionhandler:latest
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: actionhandler
  namespace: lw  
spec:
  selector:
    app: actionhandler
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080