apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: processengine
  namespace: lw  
  annotations:
    configmap.reloader.stakater.com/reload: "processengine-config"  
spec:
  selector:
    matchLabels:
      app: processengine
  replicas: 1 
  template:
    metadata:
      labels:
        app: processengine
    spec:
      containers:
      - name: processengine
        image: gcr.io/sap-se-commerce-arch/processengine:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: processengine-config
      restartPolicy: Always