#!/bin/bash

echo "Setting up RBAC for NATS controller"
kubectl apply -f https://raw.githubusercontent.com/nats-io/nats-operator/master/deploy/default-rbac.yaml

echo "Deploying NATS controller"
kubectl apply -f https://raw.githubusercontent.com/nats-io/nats-operator/master/deploy/deployment.yaml

echo "Creating NAST cluster"
echo '
apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "nats-cluster"
spec:
  size: 3
  version: "1.3.0"
' | kubectl apply -f -